### PR TITLE
use unlocked byte I/O operations

### PR DESCRIPTION
**Pull request by StefanKarpinski**
That last one didn't really work.

### CODE REVIEW

**Comment by giordano** [comment]
I think on Windows they're called [`_getc_nolock`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getc-nolock-getwc-nolock?view=vs-2019), [`_putc_nolock`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/putc-nolock-putwc-nolock?view=vs-2019), etc?

**Comment by StefanKarpinski** [comment]
Ah, ok. That's helpful. This looked like it was succeeding but then failed. Now I have all these bogus releases 😞. Might have to blow the repo away and recreate it without all the detritus.

**Comment by StefanKarpinski** [comment]
How do I detect if I'm compiling for Windows or not in the BB build environment?

**Comment by giordano** [comment]
In BB you can check the `target` environment variable.  For example, in bash
```sh
if [[  "${target}" == *-mingw* ]]; then
    # ...
fi
```

In a Makefile outside BB it's a bit more convoluted.  I've based https://github.com/JuliaStrings/utf8proc/pull/174 on what Julia does to detect Windows, as suggested by Keno.

**Pull request merged**
